const projects = [
    {
        id: 1,
        title: "HomePage",
        languages: ["HTML", "CSS", "JS"],
        type: ["Personal"],
        software: ["Intellij" , "Git"],
        thumb: "../img/homepage/logo_homepage.png", // J'ai ajouté ../ au cas où tu es dans le dossier /en/
        desc: "I created a homepage for my desktop PC. This homepage allows me to open applications via buttons accessible on the page or suggests ideas when I'm bored. I also added a dark mode for late-night use.",
        images: ["../img/homepage/mode-clair.png", "../img/homepage/mode-sombre.png"],
        github: "https://github.com/RedFoxou06/HomePage",
        link: "https://homepage.redfoxou.dev"
    },
    {
        id: 2,
        title: "ValoApp",
        languages: ["Java", "JavaFX", "FXML"],
        type: ["Personal"],
        software: ["Intellij" , "Git" , "Scene Builder", "Gradle"],
        thumb: "../img/valorant/logo_valorant.png",
        desc: "I created an application for one of my favorite games: Valorant. It is a Valorant account management app. This application is not finished, but I find it important to show it because creating it taught me a lot.",
        images: ["../img/valorant/valorant_1.png"],
        github: "https://github.com/RedFoxou06/ValoApp"
    },
    {
        id: 3,
        title: "Valorant Website",
        languages: ["HTML", "CSS", "JS"],
        type: ["Personal"],
        software: ["Intellij" , "Git"],
        thumb: "../img/site_valo/logo_valorant_site.png",
        desc: "A small website about Valorant where I present my favorite characters or maps. I also present my game statistics as well as those of one of my alt accounts. I do play other games, but it's certainly one where I've spent the most time and means a lot to me.",
        images: ["../img/site_valo/site_valo_1.png", "../img/site_valo/site_valo_2.png"],
        github: "https://github.com/RedFoxou06/site-valo",
        link: "https://valorant.redfoxou.dev"
    },
    {
        id: 4,
        title: "Brute Force Attack",
        languages: ["Python"],
        type: ["Personal"],
        software: ["PyCharm" , "Git" , "ChatGPT"],
        thumb: "../img/brut_force/logo_brut_force.png",
        desc: "I love cybersecurity and wanted to test a brute force attack. So I wrote a Python program to attempt to guess a password I initialized. I also asked ChatGPT for a similar but more performant program. Comparing our programs helped me understand certain mistakes I made. This project is educational; I do not use it to harm or share it as a hacking tool.",
        images: ["../img/brut_force/brut_force_1.png", "../img/brut_force/brut_force_2.png", "../img/brut_force/brut_force_3.png", "../img/brut_force/brut_force_4.png"],
        github: "https://github.com/RedFoxou06/brut_force"
    },
    {
        id: 5,
        title: "Password Generator",
        languages: ["Python"],
        type: ["Personal"],
        software: ["VS Code", "Git"],
        thumb: "../img/generateur_mdp/logo_generateur_mdp.png",
        desc: "After trying a brute force attack for educational purposes, I also sought to counter this type of attack, one solution being to have a strong password. So I made a password generator in Python. I'm considering putting it on an HTML page in the future.",
        images: ["../img/generateur_mdp/generateur_mdp_1.png", "../img/generateur_mdp/generateur_mdp_2.png"],
        github: "https://github.com/RedFoxou06/generateur_mdp"
    },
    {
        id: 6,
        title: "Converter",
        languages: ["HTML", "CSS", "Javascript"],
        type: ["Personal"],
        software: ["Intellij", "Git"],
        thumb: "../img/convertisseur/logo_convertisseur.png",
        desc: "Having always loved codes like in secret agent movies, I created my own code. Each character code was generated by my own password generator after modifying the desired length.",
        images: ["../img/convertisseur/convertisseur_1.png", "../img/convertisseur/convertisseur_2.png"],
        github: "https://github.com/RedFoxou06/convertisseur",
        link: "https://convertisseur.redfoxou.dev"
    },
    {
        id: 7,
        title: "MP3 Player",
        languages: ["Python"],
        type: ["Personal"],
        software: ["Pycharm", "Git"],
        thumb: "../img/lecteur_mp3/lecteur_mp3.jpg",
        desc: "I created a functional MP3 player. It is just a skeleton without design, and one feature doesn't work. You can load MP3 files, listen to them, adjust volume, and use a few other basic options.",
        images: ["../img/lecteur_mp3/lecteur_mp3_1.png"],
        github: "https://github.com/RedFoxou06/music-player-python"
    },
    {
        id: 8,
        title: "Bomberman",
        languages: ["Java", "JavaFX", "FXML"],
        type: ["Academic"],
        software: ["Intellij" , "Git" , "Scene Builder", "Gradle"],
        thumb: "../img/bomberman/logo_bomberman.png",
        desc: "We coded a Bomberman in class using JavaFX and SceneBuilder. It currently only features the board display, the character, enemies, and bomb explosions. We will be asked to improve and finish it this year.",
        images: ["../img/bomberman/bomberman_1.png", "../img/bomberman/bomberman_2.png"],
        github: "https://github.com/RedFoxou06/Bomberman"
    },
    {
        id: 9,
        title: "Water Management",
        languages: ["Java", "JavaFX", "FXML"],
        type: ["Academic"],
        software: ["Intellij" , "Git" , "Scene Builder", "Gradle"],
        thumb: "../img/gestion_eau/logo_gestion_eau.png",
        desc: "This application was created in a group during university projects. It's a simple app to manage water stocks, clients, and orders. Working in a group mainly taught us coordination and Git usage.",
        images: ["../img/gestion_eau/gestion_eau_1.png", "../img/gestion_eau/gestion_eau_2.png", "../img/gestion_eau/gestion_eau_3.png", "../img/gestion_eau/gestion_eau_4.png"],
        github: "https://github.com/RedFoxou06/appli-de-gestion-d-eau"
    },
    {
        id: 10,
        title: "2048 Game",
        languages: ["Java", "JavaFX", "FXML"],
        type: ["Academic"],
        software: ["Intellij" , "Git" , "Scene Builder", "Gradle"],
        thumb: "../img/jeu_2048/logo_jeu_2048.png",
        desc: "This is the classic 2048 game. The goal is to move tiles on the grid to combine them and reach the 2048 tile. You win when this tile appears, but you can keep playing for higher scores. This game is useful for training strategy and logical thinking.",
        images: ["../img/jeu_2048/jeu_2048_1.png"],
        github: "https://github.com/RedFoxou06/jeu-2048"
    },
    {
        id: 11,
        title: "Lights Off",
        languages: ["Java", "JavaFX", "FXML"],
        type: ["Academic"],
        software: ["Intellij" , "Git" , "Scene Builder", "Gradle"],
        thumb: "../img/lights_off/logo_lights_off.png",
        desc: "This is the classic Lights Off game. The goal is to click a light to toggle its state and its neighbors. You win when all lights are turned off. It's an excellent game to train logic and thinking skills.",
        images: ["../img/lights_off/lights_off_1.png"],
        github: "https://github.com/RedFoxou06/lights-off"
    },
    {
        id: 12,
        title: "Dashboard",
        languages: ["PHP", "HTML", "CSS", "Javascript"],
        type: ["Personal"],
        software: ["Intellij" , "Git" , "Scene Builder", "Gradle"],
        thumb: "../img/dashboard/dashboard.jpg",
        desc: "This is a web application that serves as a dashboard to track my projects. It allows adding a task and a deadline. You can then modify the status of this task: to do, in progress, or finished.",
        images: ["../img/dashboard/dashboard_1.png"],
        github: "https://github.com/RedFoxou06/dashboard",
        link: "https://dashboard.redfoxou.dev"
    }
];

let activeFilters = [];
let searchQuery = "";

const gallery = document.getElementById('gallery');
const searchInput = document.getElementById('searchInput');
const langFiltersContainer = document.getElementById('lang-filters');
const typeFiltersContainer = document.getElementById('type-filters');
const softFiltersContainer = document.getElementById('soft-filters');
const modal = document.getElementById('modal');

init();

function init() {
    renderFilters();
    renderProjects();
    searchInput.addEventListener('input', (e) => {
        searchQuery = e.target.value.toLowerCase();
        renderProjects();
    });
}

function renderFilters() {
    const allLangs = [...new Set(projects.flatMap(p => p.languages || []))];
    const allTypes = [...new Set(projects.flatMap(p => p.type || []))];
    const allSofts = [...new Set(projects.flatMap(p => p.software || []))];

    allLangs.forEach(tag => createFilterBtn(tag, 'lang', langFiltersContainer));
    allTypes.forEach(tag => createFilterBtn(tag, 'type', typeFiltersContainer));
    allSofts.forEach(tag => createFilterBtn(tag, 'soft', softFiltersContainer));
}

function createFilterBtn(tag, category, container) {
    const btn = document.createElement('div');
    btn.className = `tag ${category}`;
    btn.innerText = tag;
    btn.onclick = () => toggleFilter(tag, btn, category);
    container.appendChild(btn);
}

function toggleFilter(tag, btn, category) {

    if (category === 'type') {
        const typeButtons = typeFiltersContainer.children;

        for (let otherBtn of typeButtons) {
            if (otherBtn !== btn && otherBtn.classList.contains('active')) {
                otherBtn.classList.remove('active');
                const tagToRemove = otherBtn.innerText;
                activeFilters = activeFilters.filter(t => t !== tagToRemove);
            }
        }
    }

    if (activeFilters.includes(tag)) {
        activeFilters = activeFilters.filter(t => t !== tag);
        btn.classList.remove('active');
    } else {
        activeFilters.push(tag);
        btn.classList.add('active');
    }
    renderProjects();
}

function resetFilters() {
    activeFilters = [];
    searchQuery = "";
    searchInput.value = "";
    document.querySelectorAll('.tag').forEach(b => b.classList.remove('active'));
    renderProjects();
}

function renderProjects() {
    gallery.innerHTML = "";
    const filtered = projects.filter(p => {
        const textMatch = p.title.toLowerCase().includes(searchQuery) || p.desc.toLowerCase().includes(searchQuery);

        const pTags = [...(p.languages || []), ...(p.type || []), ...(p.software || [])];

        const tagMatch = activeFilters.length === 0 || activeFilters.every(t => pTags.includes(t));

        return textMatch && tagMatch;
    });

    if (filtered.length === 0) {
        gallery.innerHTML = `<div class="no-results">No projects match these criteria exactly.</div>`;
        return;
    }

    filtered.forEach(p => {
        const card = document.createElement('div');
        card.className = 'project-card';
        card.onclick = () => openModal(p);

        let tagsHTML = '';
        (p.languages || []).forEach(t => tagsHTML += `<span class="tag lang">${t}</span>`);
        (p.type || []).forEach(t => tagsHTML += `<span class="tag type">${t}</span>`);
        (p.software || []).forEach(t => tagsHTML += `<span class="tag soft">${t}</span>`);

        card.innerHTML = `
            <div class="card-thumb-box"><img src="${p.thumb}" alt="${p.title}"></div>
            <div class="card-content">
                <h3>${p.title}</h3>
                <p>${p.desc.substring(0, 60)}...</p>
                <div class="card-tags">${tagsHTML}</div>
            </div>
        `;
        gallery.appendChild(card);
    });
}

function openModal(p) {
    let tagsHTML = '';
    (p.languages || []).forEach(t => tagsHTML += `<span class="tag lang">${t}</span>`);
    (p.type || []).forEach(t => tagsHTML += `<span class="tag type">${t}</span>`);
    (p.software || []).forEach(t => tagsHTML += `<span class="tag soft">${t}</span>`);

    let buttonsHTML = '';
    if (p.github) {
        buttonsHTML += `
            <a href="${p.github}" target="_blank" class="btn-modal btn-github">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
                GitHub
            </a>`;
    }
    if (p.link) {
        buttonsHTML += `
            <a href="${p.link}" target="_blank" class="btn-modal btn-web">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>
                View Online
            </a>`;
    }

    // Traduction ici : "Screenshot" au lieu de "Capture d'écran" et "No screenshots available"
    const galleryHTML = p.images && p.images.length > 0
        ? p.images.map(src => `<img src="${src}" alt="Screenshot">`).join('')
        : '<p style="font-style:italic; color:#aaa;">No screenshots available.</p>';

    const modalScroll = document.querySelector('.modal-scroll');
    modalScroll.innerHTML = `
        <div class="modal-header-section">
            <img src="${p.thumb}" class="modal-logo" alt="Project Logo">
            <div class="modal-header-info">
                <h2 id="m-title">${p.title}</h2>
                <div class="modal-tags">${tagsHTML}</div>
                <div class="modal-actions">${buttonsHTML}</div>
            </div>
        </div>
        <div class="modal-body-section">
            <p id="m-desc">${p.desc}</p>
        </div>
        <div class="modal-gallery-section">
            <span class="gallery-title">Previews</span>
            <div class="screenshots-grid">
                ${galleryHTML}
            </div>
        </div>
    `;

    modal.classList.add('active');
    document.body.style.overflow = 'hidden';
}

function closeModal() {
    modal.classList.remove('active');
    document.body.style.overflow = 'auto';
}
modal.onclick = (e) => { if(e.target === modal) closeModal(); }